[package]
name = "plugin_clack_femtovg"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
clack-plugin = "0.1.1"
clack-extensions = { version = "0.1.1", features = ["gui", "state", "clack-plugin", "raw-window-handle_06"] }
baseview = { path = "../..", features = ["opengl", "tracing"] }
femtovg = "0.26"
raw-window-handle = { version = "0.6.2", features = ["std"] }
